all: program0 program1 program2 program3

program0: program0.c
	gcc -o program0 program0.c -lrt

program1: program1.c
	gcc -o program1 program1.c

program2: program2.c
	gcc -o program2 program2.c -lrt

program3: program3.c
	gcc -o program3 program3.c -lrt
